from __future__ import annotations

from pathlib import Path

from llm import complete, load_prompt


def run_analyze(run_dir: Path) -> str:
    corrected_file = run_dir / "02_transcribe" / "transcript.corrected.md"
    transcript_file = (
        corrected_file
        if corrected_file.exists()
        else run_dir / "02_transcribe" / "transcript.timestamped.md"
    )
    transcript = transcript_file.read_text(encoding="utf-8") if transcript_file.exists() else ""

    prompt_tpl = load_prompt(run_dir, "analyze.md")
    prompt = f"{prompt_tpl}\n\n输入转写稿：\n{transcript}"
    content = complete(run_dir=run_dir, task="analyze", prompt=prompt)
    if not content:
        content = "# Analysis\n\nanalysis generated by llm\n"

    out = run_dir / "03_analyze" / "analysis.md"
    out.write_text(content.strip() + "\n", encoding="utf-8")
    return content
