from __future__ import annotations

import json
from pathlib import Path

from llm import complete, load_prompt


def _build_short_fallback(transcript: str) -> str:
    first_line = next((x for x in transcript.splitlines() if x.strip()), "今天我们聊一个重要问题。")
    return (
        "# Short Script\n\n"
        "rewrite generated by llm\n\n"
        f"{first_line}\n"
    )


def _build_long_fallback(analysis: str) -> str:
    return "# Long Article\n\nrewrite generated by llm\n\n" + analysis[:500]


def run_rewrite(run_dir: Path, output: str = "both") -> dict[str, Path]:
    analysis_file = run_dir / "03_analyze" / "analysis.md"
    style_file = run_dir / "04_style" / "style_profile.json"
    corrected_file = run_dir / "02_transcribe" / "transcript.corrected.md"
    transcript_file = (
        corrected_file
        if corrected_file.exists()
        else run_dir / "02_transcribe" / "transcript.timestamped.md"
    )

    analysis = analysis_file.read_text(encoding="utf-8") if analysis_file.exists() else ""
    style = json.loads(style_file.read_text(encoding="utf-8")) if style_file.exists() else {}
    transcript = transcript_file.read_text(encoding="utf-8") if transcript_file.exists() else ""

    final_dir = run_dir / "final"
    rewrite_dir = run_dir / "05_rewrite"
    outputs: dict[str, Path] = {}

    context_payload = {
        "analysis": analysis,
        "transcript": transcript,
        "style_profile": style,
    }

    if output in {"both", "short"}:
        prompt_tpl = load_prompt(run_dir, "rewrite_short.md")
        prompt = f"{prompt_tpl}\n\n输入：\n{json.dumps(context_payload, ensure_ascii=False)}"
        short_content = complete(run_dir=run_dir, task="rewrite_short", prompt=prompt)
        if not short_content:
            short_content = _build_short_fallback(transcript)

        short = final_dir / "script.short.md"
        short.write_text(short_content.strip() + "\n", encoding="utf-8")
        outputs["short"] = short

    if output in {"both", "long"}:
        prompt_tpl = load_prompt(run_dir, "rewrite_long.md")
        prompt = f"{prompt_tpl}\n\n输入：\n{json.dumps(context_payload, ensure_ascii=False)}"
        long_content = complete(run_dir=run_dir, task="rewrite_long", prompt=prompt)
        if not long_content:
            long_content = _build_long_fallback(analysis)

        longf = final_dir / "article.long.md"
        longf.write_text(long_content.strip() + "\n", encoding="utf-8")
        outputs["long"] = longf

    diff = rewrite_dir / "diff.style-applied.md"
    diff.write_text(
        "# Style Applied Diff\n\n"
        f"- tone: {style.get('tone', 'balanced')}\n"
        f"- forbidden_count: {len(style.get('forbidden', []))}\n"
        f"- catchphrases_count: {len(style.get('catchphrases', []))}\n",
        encoding="utf-8",
    )
    outputs["diff"] = diff

    return outputs
