from pathlib import Path

from run_state import init_run
from stages.analyze import run_analyze


def test_analysis_contains_required_sections(tmp_path):
    run_dir = init_run(tmp_path, "run-1")
    transcript = run_dir / "02_transcribe" / "transcript.timestamped.md"
    transcript.write_text("[00:00] hello")

    run_analyze(run_dir=run_dir)

    content = (run_dir / "03_analyze" / "analysis.md").read_text().lower()
    assert "analysis generated by llm" in content


def test_analyze_prompt_contains_chinese_analysis_sections():
    prompt = Path("skills/video-remix/resources/prompts/analyze.md").read_text(encoding="utf-8")

    assert "## 原文的分段文稿（完整）" in prompt
    assert "## 核心论点" in prompt
    assert "## 金字塔结构拆解" in prompt
    assert "## 反对者视角" in prompt
    assert "## 传播营销视角" in prompt
