from run_state import init_run
from stages.rewrite import run_rewrite


def test_rewrite_outputs_short_long_and_diff(tmp_path):
    run_dir = init_run(tmp_path, "run-1")
    (run_dir / "03_analyze" / "analysis.md").write_text("## Topic\nX")
    (run_dir / "04_style" / "style_profile.json").write_text("{}")

    run_rewrite(run_dir=run_dir, output="both")

    short_file = run_dir / "final" / "script.short.md"
    long_file = run_dir / "final" / "article.long.md"
    assert short_file.exists()
    assert long_file.exists()
    assert (run_dir / "05_rewrite" / "diff.style-applied.md").exists()
    assert "rewrite generated by llm" in short_file.read_text(encoding="utf-8").lower()
    assert "美黑体验" not in short_file.read_text(encoding="utf-8")
