from run_state import init_run
from stages.analyze import run_analyze


def test_analysis_contains_required_sections(tmp_path):
    run_dir = init_run(tmp_path, "run-1")
    transcript = run_dir / "02_transcribe" / "transcript.timestamped.md"
    transcript.write_text("[00:00] hello")

    run_analyze(run_dir=run_dir)

    content = (run_dir / "03_analyze" / "analysis.md").read_text().lower()
    assert "analysis generated by llm" in content
