from __future__ import annotations

import json
import os
import subprocess
import tempfile
from pathlib import Path
from urllib import error, request


def project_root_from(run_dir: Path) -> Path:
    return Path(__file__).resolve().parents[1]


def load_prompt(run_dir: Path, name: str) -> str:
    path = project_root_from(run_dir) / "resources" / "prompts" / name
    return path.read_text(encoding="utf-8")


def _call_codex(prompt: str, cwd: Path) -> str | None:
    with tempfile.NamedTemporaryFile("w+", delete=False, suffix=".txt") as out:
        out_path = out.name
    try:
        cmd = [
            "codex",
            "exec",
            "--skip-git-repo-check",
            "--ephemeral",
            "--sandbox",
            "read-only",
            "--output-last-message",
            out_path,
            prompt,
        ]
        subprocess.run(cmd, cwd=str(cwd), check=True, capture_output=True, text=True, timeout=240)
        return Path(out_path).read_text(encoding="utf-8").strip()
    except (OSError, subprocess.SubprocessError, TimeoutError):
        return None
    finally:
        try:
            Path(out_path).unlink(missing_ok=True)
        except OSError:
            pass


def _call_openai(prompt: str) -> str | None:
    api_key = os.environ.get("OPENAI_API_KEY")
    if not api_key:
        return None
    base_url = os.environ.get("OPENAI_BASE_URL", "https://api.openai.com/v1").rstrip("/")
    model = os.environ.get("VIDEO_REMIX_LLM_MODEL", "gpt-4o-mini")
    payload = {
        "model": model,
        "messages": [{"role": "user", "content": prompt}],
        "temperature": 0,
    }
    req = request.Request(
        f"{base_url}/chat/completions",
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with request.urlopen(req, timeout=90) as resp:
            body = json.loads(resp.read().decode("utf-8"))
        return str(body["choices"][0]["message"]["content"]).strip()
    except (error.URLError, error.HTTPError, KeyError, json.JSONDecodeError, TimeoutError):
        return None


def complete(run_dir: Path, task: str, prompt: str) -> str | None:
    if os.environ.get("VIDEO_REMIX_FAKE_LLM") == "1":
        if task == "analyze":
            return "# Analysis\n\nanalysis generated by llm\n"
        if task == "rewrite_short":
            return "# Short Script\n\nrewrite generated by llm\n"
        if task == "rewrite_long":
            return "# Long Article\n\nrewrite generated by llm\n"
        if task == "transcript_correct":
            return json.dumps([], ensure_ascii=False)

    provider = os.environ.get("VIDEO_REMIX_LLM_PROVIDER", "agent").strip().lower()
    if provider == "agent":
        text = _call_codex(prompt, cwd=run_dir)
        if text:
            return text
        return _call_openai(prompt)
    if provider == "openai":
        text = _call_openai(prompt)
        if text:
            return text
        return _call_codex(prompt, cwd=run_dir)
    return _call_codex(prompt, cwd=run_dir) or _call_openai(prompt)
